osx_image: xcode8.3
language: objective-c
rvm:
  - 2.2
script:
  - xcodebuild clean && xcodebuild test -project ELSpace.xcodeproj -scheme ELSpace -sdk iphonesimulator10.3 -destination 'name=iPhone SE,OS=10.3' ONLY_ACTIVE_ARCH=NO
