fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    ensure_git_status_clean
    increment_build_number(xcodeproj: "ELSpace.xcodeproj")
    commit_version_bump(xcodeproj: "ELSpace.xcodeproj")
    gym(scheme: "ELSpace") # Build your app - more options available
    scan(scheme: "ELSpace")
    pilot
    
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "ELSpace") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(message: "Successfully deployed new Beta version (" + get_version_number + ") of ELSpace.")
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
