fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    ensure_git_status_clean
    scan(scheme: "ELSpace")
    gym(scheme: "ELSpace") # Build your app - more options available
    pilot
    
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "ELSpace") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  desc "Auto deploy to TestFlight if merges pull request"  
  lane :autodeploy do  
    if merges_pull_request
      # increment build number
      version = get_version_number
      latestBuildNumber = latest_testflight_build_number(version: version)
      build_number = latestBuildNumber + 1
      increment_build_number(build_number: "#{build_number}")
      # create a new keychain
      password = SecureRandom.base64
      keychain_name = "fastlane"
      ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
      ENV["MATCH_KEYCHAIN_PASSWORD"] = password

      create_keychain(
        name: keychain_name,
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        password: password
      )

      # fetch provisioning profile
      match(
        type: "appstore",
        keychain_name: keychain_name,
        keychain_password: password,
        readonly: true
      )

      # build the app
      gym(scheme: "ELSpace", clean: true)

      # upload to TestFlight
      pilot(skip_waiting_for_build_processing: true)
    end
  end  

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(message: "Successfully deployed new Beta version (" + get_version_number + ") of ELSpace.")
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
